name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  # python:3.10-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}

    - name: Build and push Docker image to ECR
      run: |
        docker build -t zxdanielwang/cicdworkshop .
        docker tag zxdanielwang/cicdworkshop:latest ${{ steps.ecr-login.outputs.registry }}/cicdworkshop:latest
        docker push ${{ steps.ecr-login.outputs.registry }}/cicdworkshop:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: cds
        service: cds-service
        task-definition: task-def.json  # located in this repo's root
        wait-for-service-stability: true
